<?php

namespace common\models;


use Yii;use yii\web\UploadedFile;

/**
 * This is the model class for table "{{%thuong_hieu}}".
 *
 * @property int $id
 * @property string $name Tên Thương Hiệu
 * @property string|null $code
 * @property string $logo
 *
 * @property SanPham[] $sanPhams
 */
class ThuongHieu extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%thuong_hieu}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name', 'code'], 'string', 'max' => 45],
            [['logo'], 'string', 'max' => 100],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Tên Thương Hiệu',
            'code' => 'Code',
            'logo' => 'Logo',
        ];
    }

    public function beforeSave($insert)
    {
        $this->code=myAPI::createCode($this->name);
        /**...*/

        $file=\yii\web\UploadedFile::getInstance($this,'logo');
        if(!is_null($file)){
            $time=time();
            $type= myAPI::get_extension($file->type);
            $ten_file=myAPI::createCode($this->name);
            $ten_file="{$time}_logo-{$ten_file}{$type}";
            $this->logo=$ten_file;
            if(!$insert){
                $thuonghieu= self::findOne($this->id); // my-logo.png
                Yii::$app->session->set('old_name_logo',$thuonghieu->logo);
            }

        }else{
            if($insert)
                //khong Upload file
            $this->logo='no-image.jpeg';
            else{
                //trong truong hop update
                //B1: Lay lai gia tri logo cu: my-logo.png
                $thuonghieu= self::findOne($this->id); // my-logo.png
                //B2: Gan gia tri logo moi bang gia tri logo cu: my-logo.png
                $this->logo=$thuonghieu->logo;
            }
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        //Upload anh sau khi luu vao CSDL thanh cong
        $file=\yii\web\UploadedFile::getInstance($this,'logo');
        if(!is_null($file)){
            $ten_file=$this->logo;
            $path=dirname(dirname(__DIR__)).'/images/'.$ten_file;
            $file->saveAs($path);

            if(!$insert){
                $ten_file_cu=Yii::$app->session->get('old_name_logo');
                if($ten_file_cu!='no-image.jpeg'){
                    $path=dirname(dirname(__DIR__)).'/images/'.$ten_file_cu;
                    if(is_file($ten_file_cu))
                        unlink($path);
                }
            }

        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function beforeDelete()
    {
        if ($this->logo !='no-image.jpeg'){
            $path=dirname(dirname(__DIR__)).'/images/'.$this->logo;
            if(is_file($path))
                unlink(@$path);
        }

        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    /**
     * Gets query for [[SanPhams]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getSanPhams()
    {
        return $this->hasMany(SanPham::className(), ['thuong_hieu_id' => 'id']);
    }


}
