<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "{{%tu_khoa}}".
 *
 * @property int $id
 * @property string $name Từ Khoá
 * @property string|null $code
 *
 * @property TuKhoaSanPham[] $tuKhoaSanPhams
 */
class TuKhoa extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%tu_khoa}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name', 'code'], 'string', 'max' => 45],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Từ Khoá',
            'code' => 'Code',
        ];
    }

    /**
     * Gets query for [[TuKhoaSanPhams]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getTuKhoaSanPhams()
    {
        return $this->hasMany(TuKhoaSanPham::className(), ['tu_khoa_id' => 'id']);
    }

    public function beforeSave($insert)
    {
        $this->code=myAPI::createCode($this->name);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
